# basics of numpy

In [1]:
#import library
#pip install numpy (uncomment to install the numpy library)
import numpy as np

In [2]:
#1D array
arr_1 = np.array([1,2,3,4,5])
arr_1

array([1, 2, 3, 4, 5])

In [3]:
#2D array also called matrix
arr_2 = np.array([[1,2,3,4,5],[6,2,8,4,10]])
arr_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  2,  8,  4, 10]])

In [4]:
#cheak dimensions
arr_2.ndim

2

In [5]:
#detail of array
np.info(arr_2)

class:  ndarray
shape:  (2, 5)
strides:  (20, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x210ce1bf0a0
byteorder:  little
byteswap:  False
type: int32


In [6]:
#cheak the shape of the matrix
arr_2.shape

(2, 5)

In [7]:
#cheak data type of the array
arr_2.dtype

dtype('int32')

In [8]:
#some useful matrix
zero_matrix=np.zeros(4)           #same for ones's and eye matrix

In [9]:
zero_matrix

array([0., 0., 0., 0.])

In [10]:
rand_a=np.random.randint(1,15,4)            # 4 random numbers between 1 and 15
print(rand_a)
rand_b=np.random.rand(5)                    #  5 random numbers
print(rand_b)
rand_c=np.random.randn(40)                  # 40 negative and positive random numbers
print(rand_c)

[11 12 14 12]
[0.16111589 0.26608096 0.13111537 0.31881143 0.45857675]
[-1.40846811 -0.29467357 -0.2226409  -0.65771914 -0.82320457 -0.65341036
 -1.25575388  0.79265864 -1.58754812  0.15910489 -0.14552973  0.15987276
  1.65311118 -0.84098361 -0.13400247  0.91994345  1.26118353 -0.25700972
 -1.91062151  1.9220858   1.74342282  0.58581415  0.98542436 -0.63691472
 -0.20809607 -0.63604884 -0.36023045  0.85217397  0.39312507  0.02704465
  0.44363671 -0.13273859  0.3895546   0.93503433  1.01941469 -0.33606048
 -0.74208865 -0.29597455  0.4998388   1.13418873]


In [11]:
#calculate the mean
np.mean(rand_a)  

12.25

In [12]:
# data reshaping
rand_c.reshape(4,10)        #multiplication of parameter should be 40. other possibilities are (10,4),(20,2)

array([[-1.40846811, -0.29467357, -0.2226409 , -0.65771914, -0.82320457,
        -0.65341036, -1.25575388,  0.79265864, -1.58754812,  0.15910489],
       [-0.14552973,  0.15987276,  1.65311118, -0.84098361, -0.13400247,
         0.91994345,  1.26118353, -0.25700972, -1.91062151,  1.9220858 ],
       [ 1.74342282,  0.58581415,  0.98542436, -0.63691472, -0.20809607,
        -0.63604884, -0.36023045,  0.85217397,  0.39312507,  0.02704465],
       [ 0.44363671, -0.13273859,  0.3895546 ,  0.93503433,  1.01941469,
        -0.33606048, -0.74208865, -0.29597455,  0.4998388 ,  1.13418873]])

In [13]:
#create array with arange function
arr_3= np.arange(1,10)  
arr_3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#cheak the size of array
arr_3.size

9

In [15]:
#seed function is used to create a same random number after every execution
np.random.seed(123)
rand_d=np.random.randint(1,100,50)
rand_d

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81, 69, 50, 56, 68,  3, 85, 40, 67, 85, 48, 62, 49,  8, 93,
       53, 98, 86, 95, 28, 35, 98, 77, 41,  4, 70, 65, 76, 35, 59, 11])

In [16]:
#3d array
rand_e = np.random.randint(0, 9, (3, 10, 2))
rand_e

array([[[6, 2],
        [4, 4],
        [6, 3],
        [0, 6],
        [4, 7],
        [6, 7],
        [1, 5],
        [7, 2],
        [4, 8],
        [1, 2]],

       [[1, 1],
        [3, 5],
        [0, 8],
        [1, 6],
        [3, 3],
        [5, 7],
        [2, 3],
        [3, 3],
        [8, 6],
        [7, 6]],

       [[3, 6],
        [6, 6],
        [1, 3],
        [4, 3],
        [1, 0],
        [5, 8],
        [6, 8],
        [1, 0],
        [3, 1],
        [3, 4]]])

In [17]:
#slicing in 1d array
print(arr_3[3])    
print(arr_3[0:4])     
print(arr_3[1:4:2])   
print(arr_3[::-1]) 

4
[1 2 3 4]
[2 4]
[9 8 7 6 5 4 3 2 1]


In [18]:
#slicing in 2d array
print(arr_2[0][1])  
print(arr_2[0,1])     
print(arr_2[:2])     
print(arr_2[:2,:2])         
print(arr_2[:2])

2
2
[[ 1  2  3  4  5]
 [ 6  2  8  4 10]]
[[1 2]
 [6 2]]
[[ 1  2  3  4  5]
 [ 6  2  8  4 10]]


In [19]:
#apply condition
arr_2[arr_2>5]

array([ 6,  8, 10])

In [20]:
#arithmetic operators
print(arr_2* 2)
print(arr_2+2)
print(arr_1+arr_2)
print(arr_1*arr_2)


[[ 2  4  6  8 10]
 [12  4 16  8 20]]
[[ 3  4  5  6  7]
 [ 8  4 10  6 12]]
[[ 2  4  6  8 10]
 [ 7  4 11  8 15]]
[[ 1  4  9 16 25]
 [ 6  4 24 16 50]]


In [21]:
# geometric functions
print(np.sum(arr_1))
print(np.sqrt(arr_1))
print(np.exp(arr_1))
print(np.sin(arr_1))
print(np.cos(arr_1))

15
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [22]:
#find the minimun and maximum values
print(np.min(arr_1))
print(np.max(arr_1))
print(np.argmin(arr_1))         #return index of the min value
print(np.argmax(arr_1))         #return the index of max value

1
5
0
4


In [23]:
#equally spaced array
arr_4=np.linspace(1,15,10)
arr_4

array([ 1.        ,  2.55555556,  4.11111111,  5.66666667,  7.22222222,
        8.77777778, 10.33333333, 11.88888889, 13.44444444, 15.        ])

In [24]:
#axis=0 w.r.t column , axis=1 w.r.t row 
print(np.min(arr_2,axis=1)) 
print(np.min(arr_2,axis=0))
print(np.sum(arr_2,axis=0))

[1 2]
[1 2 3 4 5]
[ 7  4 11  8 15]


In [25]:
# like a fabinoci series
print(np.cumsum(arr_2)) 

[ 1  3  6 10 15 21 23 31 35 45]


In [26]:
#return the unique values
print(np.unique(rand_b)) 

[0.13111537 0.16111589 0.26608096 0.31881143 0.45857675]


In [27]:
arr_4=arr_4.reshape(2,5)

In [28]:
#stacking
print(np.hstack((arr_2,arr_4)))      #horizontal stack
print(np.vstack((arr_2,arr_4)))      #vertical stack

[[ 1.          2.          3.          4.          5.          1.
   2.55555556  4.11111111  5.66666667  7.22222222]
 [ 6.          2.          8.          4.         10.          8.77777778
  10.33333333 11.88888889 13.44444444 15.        ]]
[[ 1.          2.          3.          4.          5.        ]
 [ 6.          2.          8.          4.         10.        ]
 [ 1.          2.55555556  4.11111111  5.66666667  7.22222222]
 [ 8.77777778 10.33333333 11.88888889 13.44444444 15.        ]]


# numpy indexed

In [29]:
#pip install numpy-indexed (uncomment this line to install the numy-indexed library)
import numpy_indexed as ni

In [30]:
#remove same values from the arr_2
ex =ni.exclusive(*arr_2)
ex

array([ 1,  3,  5,  6,  8, 10])

In [31]:
#calculate union of arr_2
ni.union(*arr_2)

array([ 1,  2,  3,  4,  5,  6,  8, 10])

In [32]:
#find the unique values of arr_2 and return the indicies of the same values in arr_1 and arr_2
ni.indices(ni.union(*arr_2), arr_1)

array([0, 1, 2, 3, 4], dtype=int64)